language: node_js
node_js:
- 0.10

env:
  matrix:
  - TRAVIS=true
  global:
  - secure: Vc11WwykJr058A8b71Kfaule1rfWIB4KcTfgx+Xze96AgAgJw3+LzuHfTv7gnJDakT+iapIx/H5kbMo9hghEgwEVS2aWZ/2QFeh5UBv/OFA3p5kJlDDgiNQ/q3TQY4V9lkWui2Y9a/tGJvnVmG4zh/QE/Ot9SLg9g8JvrdlxCQc=
  - secure: yJgaiEKz0QSxLvdAvyoOwBHruPW5FKfKlgwuNmdp95hzX5eNG7RK1qbq88Pf9kuUKHT4gUHjbA8wKFAgsSRs+OuxAux5gpMOI9GBEQwe3dhWet5sR/lJCqqWnzYNfB7/7xO5jMZB+jkNusCI2ebzQXNV56Amf0dFjDnqrXwdqaU=

git:
  depth: 1
  submodules: false

before_install:
- npm install -g --quiet --production grunt-cli

install:
- npm install --loglevel error --development

script:
- make lint karma